# Generated by Django 3.2.8 on 2021-10-12 08:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webcam', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='crime',
            name='image',
            field=models.CharField(default='webcam/ong.png', max_length=100),
        ),
    ]
