# Generated by Django 3.2.8 on 2021-10-12 08:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webcam', '0002_crime_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='crime',
            name='date',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
