# Generated by Django 3.2.8 on 2021-10-12 10:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webcam', '0003_alter_crime_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='crime',
            name='validated',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='crime',
            name='correct',
            field=models.BooleanField(default=False),
        ),
    ]
